# fly.toml app configuration file generated for menu-brioche-v2 on 2023-07-10T03:30:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "menu-brioche-v2"
primary_region = "bog"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
