PUT http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGU4MWNkYmRkYmY5ZTBjNDI2YzNjMiIsInVzZXJuYW1lIjoiaGFyb2xkbWpzIiwiaWF0IjoxNjg4NzA0MjgxfQ.GG0hDHudaV13VYkhypRbBXoB7UahbxaIUX-tuO4ipdc

  {
    "name": "pollo crispy",
    "price": 10.5,
    "image": "crispy.jpg",
    "description": "Pollo crujiente, tocineta, salsa cajún, queso amarillo y lechuga.",
    "category": "brioches",
    "favorite": false,
    "available": true,
    "id": "647e752f60fb5a9b2cd47f99"
  }