PUT http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGU4MWNkYmRkYmY5ZTBjNDI2YzNjMiIsInVzZXJuYW1lIjoiaGFyb2xkbWpzIiwiaWF0IjoxNjg4NzA0MjgxfQ.GG0hDHudaV13VYkhypRbBXoB7UahbxaIUX-tuO4ipdc

{
    "id" : "647e752f60fb5a9b2cd47f93",
    "name" : "camaron",
    "price" : 11.5,
    "image" : "camaron.jpg",
    "description" : "Camarones cerealizados, tártara estilo brioche, rodajas de tomate y lechuga.",
    "category" : "brioches",
    "favorite" : true,
    "available" : true
}
